version: '2'

services:
    www:
        build: www
        working_dir: /var/www/current
        depends_on:
            - mysql
            - mailcatcher
        ports:
            - ${WWW_PORT}:80
        volumes:
            - ../:/var/www/current
            - ./www/nginx/sites-available/:/etc/nginx/sites-available/
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            SF_DATABASE_HOST: mysql
            SF_DATABASE_PORT: 3306
            SF_DATABASE_NAME: sidus_filter
            SF_DATABASE_USER: sidus_filter
            SF_DATABASE_PASSWORD: sidus_filter
            SF_MAILER_TRANSPORT: smtp
            SF_MAILER_HOST: mailcatcher:1025
            SF_MAILER_USER: '~'
            SF_MAILER_PASSWORD: '~'
            SF_SECRET: 7b32d964929243dfa152ee5b1afe2199d49b1ad6
            SF_TRUSTED_PROXIES: '~'

    mysql:
        image: mariadb
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: sidus_filter
            MYSQL_USER: sidus_filter
            MYSQL_PASSWORD: sidus_filter

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - 1080:1080

volumes:
    mysql_data: ~
