sidus_filter:
    configurations:
        news:
            # Tells the system to use the Doctrine filter engine
            provider: doctrine

            # This is a variable node, you can put anything you want but some provider
            # will require specific options to work
            options:
                # Required by the doctrine provider to select the proper data source
                entity: AppBundle\Entity\News

            # Optional, default to 15
            results_per_page: 10

            # Optional, list any field you want to enable sort on
            sortable:
                - id
                - title
                - publicationDate
                - publicationStatus

            # Optional, define the default sort
            default_sort:
                publicationDate: DESC

            # Optional, define all the filters you need
            filters:
                title: ~ # Default type is text, you can leave the configuration blank

                author: # This code won't be used when you declare the "attributes" property
                    # Override the default form widget but keep the filter type logic
#                    form_type: AppBundle\Form\Type\AuthorType

                    # Search in multiple fields at the same time (using OR)
                    attributes: [author.fullName, author.email]

                # Date range example
                publicationDate:
                    type: date_range

                # Choice filter can be used for scalar values
                publicationStatus:
                    type: choice

                    # You can define a default value
                    default: [validated, published]

                    # Use form_options to provide any additional Symfony form options to the
                    # form widget
                    form_options:
                        multiple: true
                        expanded: true
#                        # Choices are optional, the filter can create a list automatically
#                        choices:
#                            Published: published
#                            Draft: draft
#                            # ....

                # Here we filter a relationship to the Category entity
                categories:
                    type: choice
                    form_options:
                        # Allows multiple choices (Standard ChoiceType option)
                        multiple: true
                    attributes: [categories.title]

                # Default filters can be hidden from the form to force filtering
                deleted:
                    default: 0

                    # This is a variable node, you can use it for you own custom needs
                    options:
                        # Hide completely this filter in the form,
                        # this is the only default option defined by this bundle
                        hidden: true
